Repository Moank/moank-open-api-docs, pull requests merged in 2024-03, with the labels that each got.

#93 [111] Add payment endpoint documentation
  specifications/factoring/factoring.yml
Labels: master, lime

#94 [Fix] Improve description new endpoint
  specifications/factoring/factoring.yml
Labels: master, lime

#96 [7088] Remove requirement of phone and email in doc
  specifications/factoring/factoring.yml
Labels: master, green

#95 [1700] Add currency in doc
  specifications/factoring/factoring.yml
Labels: master, green

#97 [3412] Document transaction bank reference id return
  specifications/factoring/factoring.yml
Labels: master
